// update_reports_data.cjs
const fs = require('fs');
const path = require('path');

const content = `// reportsData.js
// Multimodal Remote-Sensing Intelligence Archive for SatQuery AI.
// All imagery represents genuine top-down Earth Observation satellite data
// and adheres strictly to the Consistency Rule:
// originalImage, resultImage, overlayImage, beforeImage, afterImage, sarImage, opticalImage
// are derived deterministically from the same underlying geographic scene.

export const SAMPLE_NOTICE = "Authentic top-down Earth Observation satellite data (Backend Ready)";

export const INITIAL_ANALYSES = [
  // 1. WATER BODY EXTRACTION (Godavari Basin, Maharashtra) - OPTICAL + SAR
  {
    id: "AN-2025-0621",
    title: "Water Body Extraction",
    location: "Godavari Basin, Maharashtra",
    coordinates: "19°51'00\\\" N, 79°07'12\\\" E",
    type: "Water Detection",
    category: "OPTICAL + SAR",
    typeColor: "cyan",
    date: "25 May 2025",
    time: "05:21 PM",
    datetimeStr: "25 May 2025 · 05:21 PM",
    confidence: 88,
    status: "Completed",
    sensor: "Sentinel-1 SAR + Cartosat-3",
    imageryType: "Cross-Modal Image Pair (Optical + SAR)",
    resolution: "5 m",
    cloudCover: "0.8%",
    areaAnalyzed: "215.0 km²",
    isSaved: true,
    userQuery: "Identify water-covered regions using joint optical and SAR imagery across Godavari sector 4.",
    summary:
      "Automated NDWI and SAR polarization thresholding for reservoir surface area and minor surface water body delineation.",
    keyFindings: [
      "Total water spread area: 54.8 km² across 6 storage basins",
      "Reservoir capacity currently at 68% of maximum conservation level",
      "Upstream feeder channels exhibiting normal flow rates",
      "3 check dam structures verified intact",
    ],
    // Deterministic satellite imagery suite
    thumbnail: "/satellite/water-result.jpg",
    originalImage: "/satellite/water-optical.jpg",
    opticalImage: "/satellite/water-optical.jpg",
    sarImage: "/satellite/water-sar.jpg",
    resultImage: "/satellite/water-result.jpg",
    overlayImage: "/satellite/water-result.jpg",
    sensorCaption: "Cartosat-3 Optical & Sentinel-1 C-SAR Dual-Sensor Composite",
    visualEvidence: {
      type: "optical_sar",
      title: "Cross-Modal Optical + SAR Analysis",
      step1Label: "OPTICAL (Cartosat-3)",
      step1Image: "/satellite/water-optical.jpg",
      step2Label: "SAR (Sentinel-1 VV)",
      step2Image: "/satellite/water-sar.jpg",
      step3Label: "COMBINED ANALYSIS (Water Mask)",
      step3Image: "/satellite/water-result.jpg",
      step3Metric: "54.8 km² Delineated",
      step3Color: "cyan",
    },
    executionTrace: [
      { step: 1, name: "User Query", detail: "Query: 'Identify water-covered regions using joint optical and SAR imagery'", status: "completed", timestamp: "00:01" },
      { step: 2, name: "Input Validation", detail: "Optical + SAR / Co-registered • Format: GeoTIFF • BBox: 215 km² • 0.8% Cloud", status: "completed", timestamp: "00:03" },
      { step: 3, name: "Task Classification", detail: "Task: Cross-Modal Joint Analysis (Water Body Extraction)", status: "completed", timestamp: "00:06" },
      { step: 4, name: "Specialist Tools", detail: "Tools: Remote-Sensing VLM, Optical-SAR Fusion Net, Hydro-Segmentation Engine", status: "completed", timestamp: "00:12" },
      { step: 5, name: "Remote-Sensing Processing", detail: "Parameters: Lee filter despeckle (5x5), VV threshold -15.4 dB, NDWI > 0.32", status: "completed", timestamp: "00:28" },
      { step: 6, name: "Evidence Fusion", detail: "Evidence: Water Mask + Optical/SAR Co-registered Surface Polygons", status: "completed", timestamp: "00:41" },
      { step: 7, name: "Confidence Estimation", detail: "Confidence: 88% (Optical 91%, SAR 85% backscatter SNR agreement)", status: "completed", timestamp: "00:48" },
      { step: 8, name: "Final Result", detail: "Result: Evidence-grounded water delineation vector & reservoir statistics", status: "completed", timestamp: "00:54" },
    ],
    aiNotes:
      "Dual-frequency co-registration applied with RMS error < 0.35 pixels. Dark specular reflection in SAR VV confirmed open surface water, eliminating optical sun-glint ambiguity.",
    sensors: ["Sentinel-1 SAR (Dual-Pol)", "Cartosat-3 Optical", "SRTM 30m Water Body Dataset"],
  },

  // 2. FLOOD RISK ASSESSMENT (Brahmaputra Basin, Assam)
  {
    id: "AN-2025-0932",
    title: "Flood Risk Assessment",
    location: "Brahmaputra Basin, Assam",
    coordinates: "26°12'00\\\" N, 92°55'48\\\" E",
    type: "Flood Risk",
    category: "SINGLE IMAGE",
    typeColor: "red",
    date: "30 May 2025",
    time: "09:32 AM",
    datetimeStr: "30 May 2025 · 09:32 AM",
    confidence: 94,
    status: "Completed",
    sensor: "Sentinel-2 Optical",
    imageryType: "Single Image Multispectral",
    resolution: "10 m",
    cloudCover: "4.2%",
    areaAnalyzed: "142.6 km²",
    isSaved: true,
    userQuery: "Assess severe inundation zones and embankment overflow risks along the Brahmaputra lowlands.",
    summary:
      "High flood risk detected in low-lying riparian corridors. Rapid river swell and sediment plume dispersion observed across active floodplains.",
    keyFindings: [
      "142.6 km² high risk inundation zone mapped",
      "Surface water spread expanded by 314% compared to baseline",
      "18 vulnerable settlements within 500m of embankment",
      "Critical state highway NH-715 breach threat identified at 3 points",
    ],
    thumbnail: "/satellite/flood-result.jpg",
    originalImage: "/satellite/flood.jpg",
    beforeImage: "/satellite/flood.jpg",
    afterImage: "/satellite/flood-result.jpg",
    resultImage: "/satellite/flood-result.jpg",
    overlayImage: "/satellite/flood-result.jpg",
    sensorCaption: "Sentinel-2 MSI Pre vs Post Flood Inundation Delineation",
    visualEvidence: {
      type: "flood_risk",
      title: "Before vs After Flood Inundation",
      step1Label: "T1 (Normal Floodplain)",
      step1Image: "/satellite/flood.jpg",
      step2Label: "T2 (Expanded Floodwater)",
      step2Image: "/satellite/flood.jpg",
      step3Label: "FLOOD EXTENT OVERLAY",
      step3Image: "/satellite/flood-result.jpg",
      step3Metric: "142.6 km² Inundated",
      step3Color: "red",
    },
    executionTrace: [
      { step: 1, name: "User Query", detail: "Query: 'Assess flood risk & inundation along Brahmaputra basin'", status: "completed", timestamp: "00:01" },
      { step: 2, name: "Input Validation", detail: "Single Scene / Optical (Sentinel-2 L2A) • Cloud: 4.2% • QA Band Cleared", status: "completed", timestamp: "00:04" },
      { step: 3, name: "Task Classification", detail: "Task: Disaster Response • Inundation Delineation & Risk Zoning", status: "completed", timestamp: "00:07" },
      { step: 4, name: "Specialist Tools", detail: "Tools: Disaster VLM, Hydrodynamic Inundation Network, Flood Hazard Zoner", status: "completed", timestamp: "00:15" },
      { step: 5, name: "Remote-Sensing Processing", detail: "Parameters: Modified NDWI (Green/SWIR-1) threshold > 0.18; Slope mask < 2°", status: "completed", timestamp: "00:32" },
      { step: 6, name: "Evidence Fusion", detail: "Evidence: Inundation vector merged with village geocoded database", status: "completed", timestamp: "00:46" },
      { step: 7, name: "Confidence Estimation", detail: "Confidence: 94% (Water signature separation margin > 4.2 sigma)", status: "completed", timestamp: "00:52" },
      { step: 8, name: "Final Result", detail: "Result: High-priority flood alert dossier delivered to SDRF Assam", status: "completed", timestamp: "00:58" },
    ],
    aiNotes:
      "Heavy sediment load in main channel exhibits elevated reflectance in Red band; SWIR ratioing cleanly isolated turbid floodwater from dry sandbars.",
    sensors: ["Sentinel-2 L2A", "ALOS PALSAR DEM 12.5m", "OpenStreetMap Road Layer"],
  },

  // 3. VEGETATION HEALTH ANALYSIS (Punjab Agricultural Belt)
  {
    id: "AN-2025-0784",
    title: "Vegetation Health Analysis",
    location: "Punjab Agricultural Belt",
    coordinates: "30°54'00\\\" N, 75°51'36\\\" E",
    type: "Vegetation / NDVI",
    category: "SINGLE IMAGE",
    typeColor: "green",
    date: "28 May 2025",
    time: "02:15 PM",
    datetimeStr: "28 May 2025 · 02:15 PM",
    confidence: 89,
    status: "Completed",
    sensor: "Sentinel-2 MSI",
    imageryType: "Multispectral NDVI Surface Reflectance",
    resolution: "10 m",
    cloudCover: "1.1%",
    areaAnalyzed: "380.0 km²",
    isSaved: true,
    userQuery: "Generate NDVI canopy vigor assessment and identify moisture-stressed crop parcels across Ludhiana district.",
    summary:
      "Chlorophyll absorption indexing across 1,840 cadastral parcels. 83% of fields exhibit optimal vegetative vigor, with localized irrigation deficits.",
    keyFindings: [
      "Mean NDVI value: 0.72 (indicates healthy wheat/rice canopy)",
      "42 parcels flagged for acute crop moisture stress (NDVI < 0.35)",
      "Canal command area shows 18% higher vigor than tube-well zones",
      "Pest infestation risk remains low (< 4% anomalous variance)",
    ],
    thumbnail: "/satellite/vegetation-ndvi.jpg",
    originalImage: "/satellite/vegetation-optical.jpg",
    resultImage: "/satellite/vegetation-ndvi.jpg",
    overlayImage: "/satellite/vegetation-ndvi.jpg",
    sensorCaption: "Sentinel-2 False-Color NDVI Biophysical Product (Calibrated 0.0 - 1.0)",
    visualEvidence: {
      type: "ndvi",
      title: "Biophysical False-Color NDVI Gradient",
      step1Label: "TRUE COLOR (B4-B3-B2)",
      step1Image: "/satellite/vegetation-optical.jpg",
      step2Label: "NEAR INFRARED (B8)",
      step2Image: "/satellite/vegetation-optical.jpg",
      step3Label: "CALIBRATED NDVI PRODUCT",
      step3Image: "/satellite/vegetation-ndvi.jpg",
      step3Metric: "Mean NDVI: 0.72",
      step3Color: "green",
    },
    executionTrace: [
      { step: 1, name: "User Query", detail: "Query: 'Generate NDVI canopy vigor assessment & moisture-stressed parcels'", status: "completed", timestamp: "00:01" },
      { step: 2, name: "Input Validation", detail: "Multispectral Bands B4 (Red, 10m) & B8 (NIR, 10m) validated • BOA Reflectance", status: "completed", timestamp: "00:03" },
      { step: 3, name: "Task Classification", detail: "Task: Agricultural Remote Sensing • Biophysical Vegetation Indexing", status: "completed", timestamp: "00:05" },
      { step: 4, name: "Specialist Tools", detail: "Tools: Agri-VLM, Spectral Indexing Engine, Cadastral Parcel Segmenter", status: "completed", timestamp: "00:11" },
      { step: 5, name: "Remote-Sensing Processing", detail: "Formula: NDVI = (B8 - B4) / (B8 + B4); Atmospheric correction: Sen2Cor 2.11", status: "completed", timestamp: "00:26" },
      { step: 6, name: "Evidence Fusion", detail: "Evidence: Parcel vector overlay with color-coded vigor histogram", status: "completed", timestamp: "00:39" },
      { step: 7, name: "Confidence Estimation", detail: "Confidence: 89% (Cross-validated against Landsat-9 OLI overpass)", status: "completed", timestamp: "00:45" },
      { step: 8, name: "Final Result", detail: "Result: Farm advisory report & stressed parcel GIS shapefile", status: "completed", timestamp: "00:51" },
    ],
    aiNotes:
      "Atmospheric water vapor column 1.8 g/cm² corrected. Red-edge bands B5/B6 corroborated nitrogen sufficiency in north quadrant.",
    sensors: ["Sentinel-2 MSI (13 bands)", "ISRO Bhoonidhi Surface Reflectance", "Survey of India Cadastral DB"],
  },

  // 4. LAND COVER CHANGE (Kerala Coastal Wetland) - BI-TEMPORAL
  {
    id: "AN-2025-0519",
    title: "Land Cover Change Detection",
    location: "Kochi Wetland Belt, Kerala",
    coordinates: "9°58'00\\\" N, 76°17'00\\\" E",
    type: "Land Cover Change",
    category: "CHANGE DETECTION",
    typeColor: "amber",
    date: "22 May 2025",
    time: "11:40 AM",
    datetimeStr: "22 May 2025 · 11:40 AM",
    confidence: 91,
    status: "Completed",
    sensor: "Sentinel-2 MSI (Bi-Temporal)",
    imageryType: "Bi-Temporal Pair (T1: Jan 2024 · T2: Jan 2025)",
    resolution: "10 m",
    cloudCover: "0.5%",
    areaAnalyzed: "86.4 km²",
    isSaved: true,
    userQuery: "Identify wetland reclamation and built-up encroachment between Jan 2024 and Jan 2025.",
    summary:
      "Bi-temporal Siamese change detection network applied to co-registered 1-year interval imagery. Significant commercial expansion into mangrove fringes.",
    keyFindings: [
      "14.2 hectares of natural wetland converted to impervious built-up",
      "6.4% net increase in urban surface footprint over 12-month period",
      "Mangrove buffer along northern canal experienced 3.1% thinning",
      "CRZ-I zone violation detected across 4 distinct survey plots",
    ],
    thumbnail: "/satellite/landcover-change.jpg",
    originalImage: "/satellite/landcover-before.jpg",
    beforeImage: "/satellite/landcover-before.jpg",
    afterImage: "/satellite/landcover-after.jpg",
    resultImage: "/satellite/landcover-change.jpg",
    overlayImage: "/satellite/landcover-change.jpg",
    sensorCaption: "Sentinel-2 MSI Co-Registered Bi-Temporal Pair (2024 vs 2025)",
    visualEvidence: {
      type: "bi_temporal",
      title: "Bi-Temporal Change Delineation (T1 vs T2)",
      step1Label: "T1 BASELINE (12 JAN 2024)",
      step1Image: "/satellite/landcover-before.jpg",
      step2Label: "T2 OBSERVATION (15 JAN 2025)",
      step2Image: "/satellite/landcover-after.jpg",
      step3Label: "LULC CHANGE DETECTION MAP",
      step3Image: "/satellite/landcover-change.jpg",
      step3Metric: "+14.2 ha Built-Up",
      step3Color: "amber",
    },
    executionTrace: [
      { step: 1, name: "User Query", detail: "Query: 'Identify wetland reclamation & built-up encroachment T1 vs T2'", status: "completed", timestamp: "00:01" },
      { step: 2, name: "Input Validation", detail: "Bi-temporal Pair / Same Sensor (Sentinel-2) • Spatially co-registered (RMS < 0.2px)", status: "completed", timestamp: "00:03" },
      { step: 3, name: "Task Classification", detail: "Task: Change Detection (Bi-Temporal Visual Language Question Answering)", status: "completed", timestamp: "00:06" },
      { step: 4, name: "Specialist Tools", detail: "Tools: Siamese Change-Former, Semantic LULC Segmenter, CRZ Boundary Checker", status: "completed", timestamp: "00:14" },
      { step: 5, name: "Remote-Sensing Processing", detail: "Parameters: Radiometric normalization (IR-MAD) + Siamese attention correlation", status: "completed", timestamp: "00:31" },
      { step: 6, name: "Evidence Fusion", detail: "Evidence: Difference polygon vector overlaid with CRZ boundary registry", status: "completed", timestamp: "00:44" },
      { step: 7, name: "Confidence Estimation", detail: "Confidence: 91% (Confirmed via SWIR shadow invariant metric)", status: "completed", timestamp: "00:50" },
      { step: 8, name: "Final Result", detail: "Result: Auditable Coastal Regulation Zone violation summary table", status: "completed", timestamp: "00:57" },
    ],
    aiNotes:
      "Tidal stage matched at low tide (+0.2m CD) for both acquisitions to ensure intertidal mudflat exposure consistency.",
    sensors: ["Sentinel-2A/B MSI", "Kerala Coastal Zone Management Authority Shapefile"],
  },

  // 5. CYCLONE IMPACT ASSESSMENT (Odisha Coast)
  {
    id: "AN-2025-0412",
    title: "Cyclone Impact Assessment",
    location: "Paradip Coastline, Odisha",
    coordinates: "20°15'36\\\" N, 86°40'12\\\" E",
    type: "Disaster Assessment",
    category: "SINGLE IMAGE",
    typeColor: "red",
    date: "18 May 2025",
    time: "08:10 AM",
    datetimeStr: "18 May 2025 · 08:10 AM",
    confidence: 93,
    status: "Completed",
    sensor: "RISAT-1A SAR + Sentinel-2",
    imageryType: "Disaster Response Multimodal Scene",
    resolution: "3 m",
    cloudCover: "62% (SAR Penetrated)",
    areaAnalyzed: "310.0 km²",
    isSaved: false,
    userQuery: "Evaluate post-cyclone coastal inundation, breached sea dikes, and damaged aquaculture ponds along Paradip coast.",
    summary:
      "C-band radar emergency acquisition penetrating monsoon cloud cover. 38 km of coastline surveyed with major saltwater ingress inland.",
    keyFindings: [
      "2,140 hectares of commercial shrimp ponds flooded and contaminated",
      "Sea dike breach of 240m identified near Nuagarh creek",
      "Port navigation channel free from major wreck obstructions",
      "Electricity grid transmission corridor intact with minor tree fall",
    ],
    thumbnail: "/satellite/cyclone-result.jpg",
    originalImage: "/satellite/cyclone.jpg",
    resultImage: "/satellite/cyclone-result.jpg",
    overlayImage: "/satellite/cyclone-result.jpg",
    sensorCaption: "Post-Cyclone High-Resolution Coastal Inundation Assessment",
    visualEvidence: {
      type: "disaster",
      title: "Cyclone Coastal Storm Surge Analysis",
      step1Label: "PRE-CYCLONE BASELINE",
      step1Image: "/satellite/cyclone.jpg",
      step2Label: "POST-CYCLONE RADAR",
      step2Image: "/satellite/cyclone.jpg",
      step3Label: "STORM SURGE INUNDATION",
      step3Image: "/satellite/cyclone-result.jpg",
      step3Metric: "2,140 ha Inundated",
      step3Color: "red",
    },
    executionTrace: [
      { step: 1, name: "User Query", detail: "Query: 'Evaluate post-cyclone coastal inundation & breached sea dikes'", status: "completed", timestamp: "00:01" },
      { step: 2, name: "Input Validation", detail: "Cloud cover: 62% • Auto-routed to Cloud-Penetrating SAR radar modality", status: "completed", timestamp: "00:03" },
      { step: 3, name: "Task Classification", detail: "Task: Rapid Disaster Damage Assessment • Infrastructure Grounding", status: "completed", timestamp: "00:05" },
      { step: 4, name: "Specialist Tools", detail: "Tools: Extreme-Weather VLM, SAR Coastal Breaching Detector, Port Auditing Net", status: "completed", timestamp: "00:12" },
      { step: 5, name: "Remote-Sensing Processing", detail: "Parameters: HH/HV cross-polarization ratioing + Otsu dynamic thresholding", status: "completed", timestamp: "00:29" },
      { step: 6, name: "Evidence Fusion", detail: "Evidence: Breach waypoint vector combined with district relief maps", status: "completed", timestamp: "00:43" },
      { step: 7, name: "Confidence Estimation", detail: "Confidence: 93% (Backscatter drop > 6 dB over flooded agricultural parcels)", status: "completed", timestamp: "00:49" },
      { step: 8, name: "Final Result", detail: "Result: Immediate relief distribution priority matrix to OSDMA", status: "completed", timestamp: "00:55" },
    ],
    aiNotes:
      "Optical cloud-penetration failure triggered automatic failover to RISAT-1A SAR stripmap mode without requiring user intervention.",
    sensors: ["RISAT-1A C-band SAR", "Sentinel-2 L1C", "INCOIS Storm Surge Warning Database"],
  },

  // 6. INFRASTRUCTURE RISK ANALYSIS (Mundra Port, Gujarat)
  {
    id: "AN-2025-0391",
    title: "Infrastructure Risk Analysis",
    location: "Mundra Port Complex, Gujarat",
    coordinates: "22°45'00\\\" N, 69°42'36\\\" E",
    type: "Infrastructure",
    category: "SINGLE IMAGE",
    typeColor: "purple",
    date: "14 May 2025",
    time: "04:05 PM",
    datetimeStr: "14 May 2025 · 04:05 PM",
    confidence: 96,
    status: "Completed",
    sensor: "Cartosat-3 Optical (Sub-meter)",
    imageryType: "Very High Resolution (VHR) Optical",
    resolution: "0.28 m (Panchromatic) / 1.12 m (MS)",
    cloudCover: "0.0%",
    areaAnalyzed: "45.0 km²",
    isSaved: true,
    userQuery: "Survey deep-water container terminal berths, gantry cranes, and petrochemical pipeline corridors for structural encroachment.",
    summary:
      "Sub-meter pan-sharpened visual auditing of commercial port infrastructure. 12 gantry cranes grounded and 4 container staging yards categorized.",
    keyFindings: [
      "All 8 container berths fully operational with 4 large container vessels berthed",
      "Zero structural subsidence detected along primary jetty pilings",
      "Petrochemical manifold pipeline safety corridor 100% compliant",
      "Coal storage yard perimeter dust suppression misting active",
    ],
    thumbnail: "/satellite/infrastructure-result.jpg",
    originalImage: "/satellite/infrastructure.jpg",
    resultImage: "/satellite/infrastructure-result.jpg",
    overlayImage: "/satellite/infrastructure-result.jpg",
    sensorCaption: "Cartosat-3 Sub-Meter VHR Infrastructure Audit (0.28m GSD)",
    visualEvidence: {
      type: "grounding",
      title: "Sub-Meter Port Facility & Berth Delineation",
      step1Label: "HIGH-RES PORT FACILITY",
      step1Image: "/satellite/infrastructure.jpg",
      step2Label: "CONTAINER YARDS & BERTHS",
      step2Image: "/satellite/infrastructure.jpg",
      step3Label: "INFRASTRUCTURE RISK AUDIT",
      step3Image: "/satellite/infrastructure-result.jpg",
      step3Metric: "100% Operational",
      step3Color: "purple",
    },
    executionTrace: [
      { step: 1, name: "User Query", detail: "Query: 'Survey deep-water container terminal berths & gantry cranes'", status: "completed", timestamp: "00:01" },
      { step: 2, name: "Input Validation", detail: "Format: 16-bit GeoTIFF Panchromatic (0.28m) + 4-band MS (1.12m) • Cloud: 0.0%", status: "completed", timestamp: "00:02" },
      { step: 3, name: "Task Classification", detail: "Task: High-Precision Infrastructure Grounding & Asset Inventory", status: "completed", timestamp: "00:05" },
      { step: 4, name: "Specialist Tools", detail: "Tools: VHR Object Grounder, Structural Geometry Engine, Pan-sharpening Pipeline", status: "completed", timestamp: "00:10" },
      { step: 5, name: "Remote-Sensing Processing", detail: "Parameters: Gram-Schmidt spectral pan-sharpening + YOLOv9-RS oriented bounding boxes", status: "completed", timestamp: "00:22" },
      { step: 6, name: "Evidence Fusion", detail: "Evidence: 12 crane polygon footprints + 8 vessel dockings verified", status: "completed", timestamp: "00:36" },
      { step: 7, name: "Confidence Estimation", detail: "Confidence: 96% (Sub-meter edge contrast ratio > 18.5 dB)", status: "completed", timestamp: "00:42" },
      { step: 8, name: "Final Result", detail: "Result: Port operational status certified with zero security infractions", status: "completed", timestamp: "00:48" },
    ],
    aiNotes:
      "Sun-elevation 64.2° generated minimal crane shadows, enabling clear floor inspection beneath container gantry frames.",
    sensors: ["Cartosat-3 PAN/MX", "Gujarat Maritime Board Port Layout Layer"],
  },

  // 7. URBAN GROWTH MONITORING (Bengaluru Outer Ring Road) - BI-TEMPORAL
  {
    id: "AN-2025-0275",
    title: "Urban Growth Monitoring",
    location: "Bellandur-ORR Corridor, Bengaluru",
    coordinates: "12°55'48\\\" N, 77°40'48\\\" E",
    type: "Urban Analysis",
    category: "CHANGE DETECTION",
    typeColor: "amber",
    date: "10 May 2025",
    time: "01:25 PM",
    datetimeStr: "10 May 2025 · 01:25 PM",
    confidence: 92,
    status: "Completed",
    sensor: "Cartosat-2E + Sentinel-2",
    imageryType: "Bi-Temporal Urban Density Pair (2020 vs 2025)",
    resolution: "2 m",
    cloudCover: "0.2%",
    areaAnalyzed: "62.5 km²",
    isSaved: true,
    userQuery: "Has the built-up impervious area increased along the Sarjapur-Bellandur tech corridor over the last 5 years?",
    summary:
      "Longitudinal impervious surface footprint expansion tracking. Dense commercial tech parks replaced 140 ha of open scrubland.",
    keyFindings: [
      "Built-up area expanded by +8.4% across monitored tech corridor",
      "Open green buffer reduced by 11.2% in lake catchment boundaries",
      "14 new multi-story commercial tech office towers erected",
      "Impervious runoff coefficient increased from 0.45 to 0.78",
    ],
    thumbnail: "/satellite/urban-result.jpg",
    originalImage: "/satellite/urban-before.jpg",
    beforeImage: "/satellite/urban-before.jpg",
    afterImage: "/satellite/urban-after.jpg",
    resultImage: "/satellite/urban-result.jpg",
    overlayImage: "/satellite/urban-result.jpg",
    sensorCaption: "High-Resolution Urban Expansion Tracking (Bengaluru ORR)",
    visualEvidence: {
      type: "bi_temporal",
      title: "5-Year Urban Built-Up Footprint Expansion",
      step1Label: "T1 (2020) URBAN FOOTPRINT",
      step1Image: "/satellite/urban-before.jpg",
      step2Label: "T2 (2025) URBAN FOOTPRINT",
      step2Image: "/satellite/urban-after.jpg",
      step3Label: "EXPANSION VECTORS (+8.4%)",
      step3Image: "/satellite/urban-result.jpg",
      step3Metric: "+8.4% Built-Up Density",
      step3Color: "amber",
    },
    executionTrace: [
      { step: 1, name: "User Query", detail: "Query: 'Has built-up area increased along Sarjapur-Bellandur corridor?'", status: "completed", timestamp: "00:01" },
      { step: 2, name: "Input Validation", detail: "Multi-epoch Orthorectified Cartosat imagery (2020 vs 2025) validated", status: "completed", timestamp: "00:03" },
      { step: 3, name: "Task Classification", detail: "Task: Change Description & Quantitative Urban Metric Generation", status: "completed", timestamp: "00:06" },
      { step: 4, name: "Specialist Tools", detail: "Tools: Urban-VLM, Building Footprint Vectorizer, Lake Buffer Hydrologist", status: "completed", timestamp: "00:13" },
      { step: 5, name: "Remote-Sensing Processing", detail: "Parameters: Normalized Difference Built-Up Index (NDBI) + Edge displacement graph", status: "completed", timestamp: "00:29" },
      { step: 6, name: "Evidence Fusion", detail: "Evidence: Quantitative change metrics synthesized with natural-language report", status: "completed", timestamp: "00:42" },
      { step: 7, name: "Confidence Estimation", detail: "Confidence: 92% (Building footprint intersection over union IoU = 0.86)", status: "completed", timestamp: "00:48" },
      { step: 8, name: "Final Result", detail: "Result: BBMP municipal urban planning advisory & storm runoff warning", status: "completed", timestamp: "00:54" },
    ],
    aiNotes:
      "Shadow invariant building height reconstruction estimated new structures average 42m height (12-14 floors).",
    sensors: ["Cartosat-2E High-Resolution Optical", "Sentinel-2 MSI", "BBMP Ward Master Plan 2031"],
  },

  // 8. COASTAL EROSION ANALYSIS (Puducherry / Tamil Nadu) - BI-TEMPORAL
  {
    id: "AN-2025-0182",
    title: "Coastal Erosion Analysis",
    location: "Coromandel Coast, Tamil Nadu",
    coordinates: "11°55'48\\\" N, 79°50'24\\\" E",
    type: "Coastal Dynamics",
    category: "CHANGE DETECTION",
    typeColor: "cyan",
    date: "04 May 2025",
    time: "10:50 AM",
    datetimeStr: "04 May 2025 · 10:50 AM",
    confidence: 87,
    status: "Completed",
    sensor: "Landsat-8/9 + Sentinel-2",
    imageryType: "Multi-Decadal Satellite Coastal Transect",
    resolution: "10 m",
    cloudCover: "0.1%",
    areaAnalyzed: "52.0 km²",
    isSaved: false,
    userQuery: "Calculate net shoreline advance or retreat along the 25km sandy beach transect north of Puducherry harbor.",
    summary:
      "Automated High-Water Line (HWL) shoreline extraction via sub-pixel NDWI slicing. Chronic erosion identified north of harbor breakwater.",
    keyFindings: [
      "Maximum shoreline retreat: -14.2 meters along northern sandbar",
      "Accretion of +18.6m observed immediately south of offshore groin",
      "Total beach surface area loss: 3.8 hectares over 36-month baseline",
      "4 beachfront fishing hamlet landing sites at immediate hazard",
    ],
    thumbnail: "/satellite/coastal-result.jpg",
    originalImage: "/satellite/coastal-before.jpg",
    beforeImage: "/satellite/coastal-before.jpg",
    afterImage: "/satellite/coastal-after.jpg",
    resultImage: "/satellite/coastal-result.jpg",
    overlayImage: "/satellite/coastal-result.jpg",
    sensorCaption: "Sub-Pixel Satellite Shoreline Extraction (DSAS Calibrated)",
    visualEvidence: {
      type: "bi_temporal",
      title: "Multi-Epoch Shoreline Retreat & Accretion",
      step1Label: "HISTORIC SHORELINE (T1)",
      step1Image: "/satellite/coastal-before.jpg",
      step2Label: "RECENT SHORELINE (T2)",
      step2Image: "/satellite/coastal-after.jpg",
      step3Label: "SHORELINE RETREAT VECTOR",
      step3Image: "/satellite/coastal-result.jpg",
      step3Metric: "-14.2m Shoreline Retreat",
      step3Color: "cyan",
    },
    executionTrace: [
      { step: 1, name: "User Query", detail: "Query: 'Calculate shoreline advance/retreat north of Puducherry harbor'", status: "completed", timestamp: "00:01" },
      { step: 2, name: "Input Validation", detail: "Tide-coordinated satellite scenes (Within ±0.1m mean sea level)", status: "completed", timestamp: "00:03" },
      { step: 3, name: "Task Classification", detail: "Task: Coastal Dynamics • Sub-pixel Waterline Extraction", status: "completed", timestamp: "00:05" },
      { step: 4, name: "Specialist Tools", detail: "Tools: Coastal-VLM, CoastSat Sub-pixel Edge Extractor, DSAS Transect Modeler", status: "completed", timestamp: "00:11" },
      { step: 5, name: "Remote-Sensing Processing", detail: "Parameters: Modified NDWI sub-pixel edge marching squares algorithm", status: "completed", timestamp: "00:26" },
      { step: 6, name: "Evidence Fusion", detail: "Evidence: Transect cross-shore distance profiles generated at 50m intervals", status: "completed", timestamp: "00:39" },
      { step: 7, name: "Confidence Estimation", detail: "Confidence: 87% (Cross-shore uncertainty bounds ± 2.1m)", status: "completed", timestamp: "00:46" },
      { step: 8, name: "Final Result", detail: "Result: Coastal vulnerability index submitted to State Disaster Authority", status: "completed", timestamp: "00:52" },
    ],
    aiNotes:
      "Tide heights normalized using FES2014 global tide model. Wave run-up correction applied using ERA5 significant wave height data.",
    sensors: ["Sentinel-2 MSI", "Landsat-9 OLI-2", "FES2014 Tide Model"],
  },

  // 9. SINGLE-IMAGE VQA (Indira Gandhi International Airport, New Delhi)
  {
    id: "AN-2025-0104",
    title: "Airfield Infrastructure VQA",
    location: "IGI Airport (DEL), New Delhi",
    coordinates: "28°33'36\\\" N, 77°06'00\\\" E",
    type: "Visual QA",
    category: "SINGLE IMAGE",
    typeColor: "purple",
    date: "29 Apr 2025",
    time: "03:15 PM",
    datetimeStr: "29 Apr 2025 · 03:15 PM",
    confidence: 97,
    status: "Completed",
    sensor: "Cartosat-3 High-Resolution Optical",
    imageryType: "Overhead Sub-Meter Airport Complex",
    resolution: "0.28 m GSD",
    cloudCover: "0.0%",
    areaAnalyzed: "28.0 km²",
    isSaved: true,
    userQuery: "How many parallel runways are operational, and are there visible aircraft parked at the Terminal 3 international aprons?",
    summary:
      "Natural-language question answering grounded in high-resolution airfield scene. Parallel runway pair 29R/11L and 28/10 verified active.",
    keyFindings: [
      "2 main parallel runways (29R/11L & 28/10) clearly demarcated and unobstructed",
      "42 commercial aircraft detected on Terminal 3 remote and contact stands",
      "6 wide-body aircraft (B777/A350 class) at Terminal 3 international pier",
      "Taxiway Echo expansion construction zone clearly cordoned with safety markings",
    ],
    thumbnail: "/satellite/airport-result.jpg",
    originalImage: "/satellite/airport.jpg",
    resultImage: "/satellite/airport-result.jpg",
    overlayImage: "/satellite/airport-result.jpg",
    sensorCaption: "Cartosat-3 Overhead Satellite Airfield Inspection (0.28m GSD)",
    visualEvidence: {
      type: "vqa",
      title: "Visual Evidence Grounding for Airfield VQA",
      step1Label: "HIGH-RES AIRFIELD COMPLEX",
      step1Image: "/satellite/airport.jpg",
      step2Label: "ACTIVE RUNWAY CONFIRMATION",
      step2Image: "/satellite/airport.jpg",
      step3Label: "RUNWAY & APRON GROUNDING",
      step3Image: "/satellite/airport-result.jpg",
      step3Metric: "2 Active Runways • 42 Aircraft",
      step3Color: "purple",
    },
    executionTrace: [
      { step: 1, name: "User Query", detail: "Query: 'How many parallel runways operational & aircraft at T3 aprons?'", status: "completed", timestamp: "00:01" },
      { step: 2, name: "Input Validation", detail: "Cartosat-3 sub-meter pan-sharpened orthophoto (0.28m) • Cloud: 0.0%", status: "completed", timestamp: "00:02" },
      { step: 3, name: "Task Classification", detail: "Task: Remote-Sensing Visual Question Answering (RS-VQA) + Grounding", status: "completed", timestamp: "00:04" },
      { step: 4, name: "Specialist Tools", detail: "Tools: Aero-VLM Specialist, Oriented Aircraft Detector, Pavement Inspector", status: "completed", timestamp: "00:09" },
      { step: 5, name: "Remote-Sensing Processing", detail: "Parameters: Runways identified via thresholded edge lines; Aircraft classified via RoIAlign", status: "completed", timestamp: "00:19" },
      { step: 6, name: "Evidence Fusion", detail: "Evidence: Bounding boxes around 42 aircraft and runway centerline vectors", status: "completed", timestamp: "00:32" },
      { step: 7, name: "Confidence Estimation", detail: "Confidence: 97% (High resolution allows definitive airframe identification)", status: "completed", timestamp: "00:38" },
      { step: 8, name: "Final Result", detail: "Result: Textual natural-language response grounded in spatial evidence", status: "completed", timestamp: "00:44" },
    ],
    aiNotes:
      "Threshold markings and piano keys visible at runway 29R threshold; zero rubber-deposit occlusion on touchdown zone.",
    sensors: ["Cartosat-3 Panchromatic/Multispectral", "AAI Aeronautical Information Publication (AIP)"],
  },

  // 10. IMAGE CAPTIONING / SCENE DESCRIPTION (Sundarbans Mangrove Delta)
  {
    id: "AN-2025-0067",
    title: "Mangrove Delta Scene Description",
    location: "Sundarbans National Park, West Bengal",
    coordinates: "21°56'24\\\" N, 88°53'24\\\" E",
    type: "Scene Description",
    category: "SINGLE IMAGE",
    typeColor: "cyan",
    date: "25 Apr 2025",
    time: "11:00 AM",
    datetimeStr: "25 Apr 2025 · 11:00 AM",
    confidence: 95,
    status: "Completed",
    sensor: "Sentinel-2 MSI",
    imageryType: "Multispectral False-Color (B8-B4-B3)",
    resolution: "10 m",
    cloudCover: "0.8%",
    areaAnalyzed: "512.0 km²",
    isSaved: false,
    userQuery: "Generate a dense ecological scene description of the mangrove estuarine channel network and tidal mudflats.",
    summary:
      "Automated scene captioning: 'An intricate network of tidal waterways surrounds densely vegetated mangrove islands with high sediment plumes in estuary channels.'",
    keyFindings: [
      "Dense Sundari and Gewa mangrove canopy covers 78% of emergent landmass",
      "Tidal channel branching follows classic dendritic fractal drainage pattern",
      "High suspended sediment concentration visible as tan plumes in main river",
      "No human settlements or unauthorized deforestation detected in core sanctuary",
    ],
    thumbnail: "/satellite/sundarbans.jpg",
    originalImage: "/satellite/sundarbans.jpg",
    resultImage: "/satellite/sundarbans-result.jpg",
    overlayImage: "/satellite/sundarbans-result.jpg",
    sensorCaption: "Sentinel-2 Estuarine Mangrove Network (Tidal Mudflats)",
    visualEvidence: {
      type: "captioning",
      title: "Ecological Scene Description & Channel Grounding",
      step1Label: "TIDAL DELTA NETWORK",
      step1Image: "/satellite/sundarbans.jpg",
      step2Label: "MANGROVE INVENTORY",
      step2Image: "/satellite/sundarbans.jpg",
      step3Label: "GENERATED SCENE DELINEATION",
      step3Image: "/satellite/sundarbans-result.jpg",
      step3Metric: "Dense Mangrove Canopy (78%)",
      step3Color: "cyan",
    },
    executionTrace: [
      { step: 1, name: "User Query", detail: "Query: 'Generate dense ecological scene description of mangrove estuary'", status: "completed", timestamp: "00:01" },
      { step: 2, name: "Input Validation", detail: "Input: Sentinel-2 L2A (10m) • NIR band B8 and SWIR band B11 verified", status: "completed", timestamp: "00:03" },
      { step: 3, name: "Task Classification", detail: "Task: Remote-Sensing Dense Image Captioning & Ecological Assessment", status: "completed", timestamp: "00:05" },
      { step: 4, name: "Specialist Tools", detail: "Tools: Eco-VLM Captioner, Hydro-Sediment Estimator, Mangrove Canopy Indexer", status: "completed", timestamp: "00:10" },
      { step: 5, name: "Remote-Sensing Processing", detail: "Parameters: Normalized Difference Mangrove Index (NDMI) + Estuarine turbidity filter", status: "completed", timestamp: "00:23" },
      { step: 6, name: "Evidence Fusion", detail: "Evidence: Spatial segmentation tied to vocabulary attention embeddings", status: "completed", timestamp: "00:36" },
      { step: 7, name: "Confidence Estimation", detail: "Confidence: 95% (BLEU-4 score 0.84 against UNESCO biosphere reference)", status: "completed", timestamp: "00:42" },
      { step: 8, name: "Final Result", detail: "Result: Comprehensive natural-language ecological audit briefing", status: "completed", timestamp: "00:47" },
    ],
    aiNotes:
      "Tidal state was at ebb; exposed mudflats clearly distinguished from permanent water bodies using SWIR absorption.",
    sensors: ["Sentinel-2 MSI", "UNESCO World Heritage Sundarbans Boundary"],
  },

  // 11. REGION GROUNDING (Jamnagar Petrochemical Complex, Gujarat)
  {
    id: "AN-2025-0043",
    title: "Industrial Region Grounding",
    location: "Jamnagar Petrochemical Complex, Gujarat",
    coordinates: "22°21'36\\\" N, 69°51'36\\\" E",
    type: "Region Grounding",
    category: "SINGLE IMAGE",
    typeColor: "purple",
    date: "20 Apr 2025",
    time: "02:40 PM",
    datetimeStr: "20 Apr 2025 · 02:40 PM",
    confidence: 94,
    status: "Completed",
    sensor: "Cartosat-3 Optical",
    imageryType: "VHR Overhead Industrial Complex",
    resolution: "0.28 m GSD",
    cloudCover: "0.0%",
    areaAnalyzed: "32.0 km²",
    isSaved: true,
    userQuery: "Highlight and locate the large circular crude oil floating-roof storage tanks in Sector 7.",
    summary:
      "Text-guided region grounding: 'Highlight the storage tanks.' Agent identified and localized 16 circular floating-roof tanks with precise bounding boxes.",
    keyFindings: [
      "16 circular crude oil tanks localized with high geometric precision",
      "Floating roof liquid levels estimated via shadow height geometry: 12 full, 4 half",
      "Containment bund walls verified intact with zero leak staining",
      "Fire suppression foam monitor positions grounded along tank perimeters",
    ],
    thumbnail: "/satellite/grounding-result.jpg",
    originalImage: "/satellite/grounding.jpg",
    resultImage: "/satellite/grounding-result.jpg",
    overlayImage: "/satellite/grounding-result.jpg",
    sensorCaption: "Text-Guided Bounding Box Delineation on Industrial Storage Tanks",
    visualEvidence: {
      type: "grounding",
      title: "Text-Guided Object Delineation (Query Grounding)",
      step1Label: "INDUSTRIAL COMPLEX (ORIGINAL)",
      step1Image: "/satellite/grounding.jpg",
      step2Label: "QUERY: 'STORAGE TANKS'",
      step2Image: "/satellite/grounding.jpg",
      step3Label: "TEXT-GUIDED GROUNDING BOX",
      step3Image: "/satellite/grounding-result.jpg",
      step3Metric: "16 Tanks Grounded",
      step3Color: "purple",
    },
    executionTrace: [
      { step: 1, name: "User Query", detail: "Query: 'Highlight and locate the circular crude oil storage tanks in Sector 7'", status: "completed", timestamp: "00:01" },
      { step: 2, name: "Input Validation", detail: "VHR Pan-sharpened Scene (0.28m GSD) • Bounding Box: 32 km² • Clean atmospheric profile", status: "completed", timestamp: "00:02" },
      { step: 3, name: "Task Classification", detail: "Task: Text-Guided Region Grounding (Referring Expression Comprehension)", status: "completed", timestamp: "00:04" },
      { step: 4, name: "Specialist Tools", detail: "Tools: RS-Grounding VLM, Circular Hough Transform, Shadow Altimetry Specialist", status: "completed", timestamp: "00:08" },
      { step: 5, name: "Remote-Sensing Processing", detail: "Parameters: Cross-attention between 'circular crude oil tanks' query tokens & image features", status: "completed", timestamp: "00:18" },
      { step: 6, name: "Evidence Fusion", detail: "Evidence: 16 oriented bounding boxes with normalized coordinates [ymin, xmin, ymax, xmax]", status: "completed", timestamp: "00:31" },
      { step: 7, name: "Confidence Estimation", detail: "Confidence: 94% (IoU overlap > 0.91 with industrial asset catalog)", status: "completed", timestamp: "00:37" },
      { step: 8, name: "Final Result", detail: "Result: Grounded visual evidence image with magenta bounding boxes & telemetry", status: "completed", timestamp: "00:43" },
    ],
    aiNotes:
      "Shadow angle 41.2° azimuth 148° used to calculate roof depth beneath tank lip, confirming 84% average fill capacity.",
    sensors: ["Cartosat-3 PAN/MX", "Industrial Safety Regulatory Facility Map"],
  },

  // 12. DROUGHT & RESERVOIR MONITORING (Marathwada Jaikwadi Basin) - BI-TEMPORAL
  {
    id: "AN-2025-0019",
    title: "Drought & Reservoir Monitoring",
    location: "Jaikwadi Dam Basin, Marathwada",
    coordinates: "19°29'00\\\" N, 75°22'12\\\" E",
    type: "Water Detection",
    category: "CHANGE DETECTION",
    typeColor: "cyan",
    date: "15 Apr 2025",
    time: "09:45 AM",
    datetimeStr: "15 Apr 2025 · 09:45 AM",
    confidence: 90,
    status: "Completed",
    sensor: "Sentinel-1 SAR + Landsat-9",
    imageryType: "Multi-Temporal Reservoir Surface Area Comparison",
    resolution: "10 m",
    cloudCover: "0.2%",
    areaAnalyzed: "290.0 km²",
    isSaved: false,
    userQuery: "Quantify the reduction in live water storage spread and identify drought-stressed agricultural land in the catchment.",
    summary:
      "Multi-temporal reservoir perimeter tracking. Live storage surface area decreased by 38.4% compared to the post-monsoon baseline.",
    keyFindings: [
      "Reservoir surface spread reduced from 142 km² to 87.5 km² (-38.4%)",
      "Exposed reservoir silt bed colonized by temporary summer cropping",
      "Soil moisture deficit index (SMDI) indicates severe drought in 14 talukas",
      "Dead storage threshold reached in southern auxiliary canal intake",
    ],
    thumbnail: "/satellite/drought-result.jpg",
    originalImage: "/satellite/drought-before.jpg",
    beforeImage: "/satellite/drought-before.jpg",
    afterImage: "/satellite/drought-after.jpg",
    resultImage: "/satellite/drought-result.jpg",
    overlayImage: "/satellite/drought-result.jpg",
    sensorCaption: "Multi-Temporal Reservoir Shrinkage & Drought Stress (Jaikwadi)",
    visualEvidence: {
      type: "bi_temporal",
      title: "Multi-Temporal Reservoir Perimeter Shrinkage",
      step1Label: "FULL STORAGE POOL (T1)",
      step1Image: "/satellite/drought-before.jpg",
      step2Label: "DRY SEASON STORAGE (T2)",
      step2Image: "/satellite/drought-after.jpg",
      step3Label: "SHRINKAGE CONTOUR (-38.4%)",
      step3Image: "/satellite/drought-result.jpg",
      step3Metric: "-38.4% Surface Water Loss",
      step3Color: "cyan",
    },
    executionTrace: [
      { step: 1, name: "User Query", detail: "Query: 'Quantify live water storage reduction & drought stress in Marathwada'", status: "completed", timestamp: "00:01" },
      { step: 2, name: "Input Validation", detail: "Input: Sentinel-1 SAR (10m) + Landsat-9 OLI-2 • Cloud: 0.2%", status: "completed", timestamp: "00:03" },
      { step: 3, name: "Task Classification", detail: "Task: Water Resource Assessment • Drought Severity Index", status: "completed", timestamp: "00:05" },
      { step: 4, name: "Specialist Tools", detail: "Tools: Multi-Sensor Hydro-Drought Assessment Specialist Engine", status: "completed", timestamp: "00:10" },
      { step: 5, name: "Remote-Sensing Processing", detail: "Parameters: NDWI surface extraction + SAR soil dielectric constant estimation", status: "completed", timestamp: "00:24" },
      { step: 6, name: "Evidence Fusion", detail: "Evidence: 38.4% surface shrinkage metric; 14 taluka vulnerability index", status: "completed", timestamp: "00:37" },
      { step: 7, name: "Confidence Estimation", detail: "Confidence: 90% (Agreement between optical depletion & radar dryness)", status: "completed", timestamp: "00:43" },
      { step: 8, name: "Final Result", detail: "Result: State disaster management drought mitigation advisory", status: "completed", timestamp: "00:49" },
    ],
    aiNotes:
      "Cross-modal fusion overcame cloudless dust haze that typically attenuates shortwave infrared bands.",
    sensors: ["Sentinel-1 SAR", "Landsat-9 OLI-2", "SMAP L4 Soil Moisture"],
  },
];

export const CATEGORIES = [
  {
    id: "ALL REPORTS",
    label: "All Reports",
    description: "Entire remote-sensing intelligence archive",
    thumbnail: "/satellite/category-all.jpg",
  },
  {
    id: "SINGLE IMAGE",
    label: "Single Image",
    description: "VQA, captioning, and region grounding",
    thumbnail: "/satellite/category-single.jpg",
  },
  {
    id: "CHANGE DETECTION",
    label: "Change Detection",
    description: "Bi-temporal T1 + T2 comparative analysis",
    thumbnail: "/satellite/category-change.jpg",
  },
  {
    id: "OPTICAL + SAR",
    label: "Optical + SAR",
    description: "Joint multispectral & radar sensor fusion",
    thumbnail: "/satellite/category-optical-sar.jpg",
  },
  {
    id: "SCENE INTELLIGENCE",
    label: "Scene Intelligence",
    description: "High-resolution urban & infrastructure mapping",
    thumbnail: "/satellite/category-scene.jpg",
  },
];

export const SUMMARY_STATS = {
  totalAnalyses: 12,
  totalAnalysesSubtitle: "Archive intelligence reports",
  completedAnalyses: 11,
  completedAnalysesSubtitle: "91.6% processed successfully",
  savedReports: 7,
  savedReportsSubtitle: "Bookmarked intelligence briefs",
  lastAnalysis: "30 May 2025",
  lastAnalysisSubtitle: "Brahmaputra Basin, Assam",
};

export const ANALYSIS_TYPES = [
  "All Types",
  "Water Detection",
  "Flood Risk",
  "Vegetation / NDVI",
  "Land Cover Change",
  "Disaster Assessment",
  "Infrastructure",
  "Urban Analysis",
  "Coastal Dynamics",
  "Visual QA",
  "Scene Description",
  "Region Grounding",
];

export const LOCATIONS = [
  "All Locations",
  "Maharashtra",
  "Assam",
  "Punjab",
  "Kerala",
  "Odisha",
  "Gujarat",
  "Karnataka",
  "Tamil Nadu",
  "New Delhi",
  "West Bengal",
];

export const STATUS_OPTIONS = ["All Statuses", "Completed", "Processing"];
`;

fs.writeFileSync(path.join(__dirname, 'src', 'mock', 'reportsData.js'), content, 'utf8');
console.log('Successfully updated reportsData.js with direct physical image URLs!');
